#!/bin/bash
# Write a script which delete an ACTIVE user on the VM

export NAME=$(whoami)
su --preserve-environment -c 'passwd -l $NAME; \
ps -fp $(pgrep -u $NAME); killall -KILL -u $NAME; userdel -r -f $NAME'

###
echo "Which user would you like to delete ?"
read username

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

check_exist=`cat /etc/passwd | grep $username`
if [ "$check_exist" != "$NULL" ]; then
	sudo passwd -l $username
	if [ "$(pgrep -u $username)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $username)
	fi
	sudo userdel -r $username
	echo "${green}USER WAS SUCCESSFULLY DELETE"
else
	echo "${red}user doesn't exist"
fi