#!/bin/bash
# Write a script which delete an ACTIVE user on the VM

export NAME=$(whoami)
su --preserve-environment -c 'passwd -l $NAME; \
ps -fp $(pgrep -u $NAME); killall -KILL -u $NAME; userdel -r -f $NAME'


####
# To list all users:
cut -d: -f1 /etc/passwd
# To remove user:
sudo userdel username

#####
# or scripts for more advanced:
sudo deluser --remove-home user
# or
sudo deluser --remove-all-files user